#create 
spring.application.name=demo
spring.datasource.url=jdbc:h2:file:./data/demo
#put your choosen username here
spring.datasource.username=YOUR_USERNAME
#put your choosen password here
spring.datasource.password=YOUR_PASSWORD
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#put the secret here
jwt.secret=YOUR_SECRET