CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    role ENUM('ADMIN', 'USER')
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category ENUM('ACTION', 'ADVENTURE', 'HORROR') NOT NULL,
    name VARCHAR(255) NOT NULL,
    language VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    release_date TIMESTAMP(6) NOT NULL,
    duration NUMERIC(21, 0) NOT NULL
);

CREATE TABLE user_movie_list (
    movie_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,

    PRIMARY KEY (movie_id, user_id),

    CONSTRAINT fk_user_movie_list_movie
        FOREIGN KEY (movie_id) REFERENCES movie(id),

    CONSTRAINT fk_user_movie_list_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);
