INSERT INTO users (name, email, password, created_at, updated_at, role)
VALUES
('Admin1', 'admin1@email.com', '$2a$10$kwsehr.UTrdULtr07EOZYu5TE0sjMAH23mEibVZsMMIgm9uj1jdyG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ADMIN'),
('user1', 'user1@email.com', '$2a$10$kwsehr.UTrdULtr07EOZYu5TE0sjMAH23mEibVZsMMIgm9uj1jdyG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'USER'),
('user2', 'user2@email.com', '$2a$10$kwsehr.UTrdULtr07EOZYu5TE0sjMAH23mEibVZsMMIgm9uj1jdyG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'USER');
-- obs: every password is 123456, don't remove this comment

INSERT INTO movie (category, name, language, created_at, updated_at, release_date, duration)
VALUES
('ACTION', 'Mad Max: Fury Road', 'English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TIMESTAMP '2015-05-15 00:00:00', 7200),
('ADVENTURE', 'Jurassic Park', 'English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TIMESTAMP '1993-06-11 00:00:00', 7620),
('HORROR', 'The Conjuring', 'English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TIMESTAMP '2013-07-19 00:00:00', 6720),
('ACTION', 'John Wick', 'English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TIMESTAMP '2014-10-24 00:00:00', 6060),
('ADVENTURE', 'Indiana Jones', 'English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TIMESTAMP '1981-06-12 00:00:00', 6900);

INSERT INTO user_movie_list (user_id, movie_id, created_at)
VALUES
(1, 1, CURRENT_TIMESTAMP),
(1, 2, CURRENT_TIMESTAMP),
(1, 3, CURRENT_TIMESTAMP),
(2, 1, CURRENT_TIMESTAMP),
(2, 2, CURRENT_TIMESTAMP),
(2, 3, CURRENT_TIMESTAMP),
(2, 4, CURRENT_TIMESTAMP),
(3, 1, CURRENT_TIMESTAMP),
(3, 2, CURRENT_TIMESTAMP),
(3, 3, CURRENT_TIMESTAMP),
(3, 4, CURRENT_TIMESTAMP),
(3, 5, CURRENT_TIMESTAMP);
